### ISSUE TITLE
Unnecessary wasm binaries

### ISSUE THREAD

**Issue by larry0x** [mars-protocol/red-bank#333]
Currently when we run `cargo make rust-optimizer`, the following two wasm binaries are generated:

```plain
mars_rewards_collector_base-aarch64.wasm
mars_zapper_base-aarch64.wasm
```

However these two are not actually used (not to be deployed on a chain).

We can avoid compiling them by removing the following line from their `Cargo.toml`s:

```toml
[lib]
crate-type = ["cdylib", "rlib"] # remove!!
```
